### ISSUE TITLE
Remove unexpected behavior on 'NAMESPACE' env variable

### ISSUE THREAD

**Issue by KevinDukelow5** [colpal/actions-gcr-buildpush#2]
The below example is required to run the CI effectively when being used with an env variable called 'NAMESPACE'. If the removal of this env is not performed the BP action will insert the value of namespace into the repo path unexpectedly.

```
      - name: Set up variables by branch
        run: ./ci/env_by_branch.sh

      - name: Remove namespace env because it messes with the next action
        run: echo "::set-env name=NAMESPACE::"

      - name: Docker build and push
        uses: colpal/actions-gcr-buildpush@cache
        with:
          gcr_service_account: ${{ secrets.PRD_GCP_SA_GCR_KEY }}
          gcr_project: 'cp-saa-external-sales-prd'
          gcr_repo: 'airflow/'
          dockerfile_path: 'containers/generic/trigger_dag_pubsub/'
          gcr_image_name: 'trigger_dag_pubsub'
          image_tag: ${{ env.PREFIX }}
```
